### ISSUE TITLE
samenvatting ai

### ISSUE THREAD

**Issue by JO0st** [KULeuven-CS/kuleuven-cs.github.io#4]
Ik heb vorig semester al een samenvatting voor AI gemaakt en die op github gezet, deze mag gerust naar hier verplaatst worden.
https://github.com/JO0st/samenvatting_AI

**Comment by JDevlieghere** [comment]
Done!

**Comment by NorfairKing** [comment]
Staat de studentencursus aI er al bij?

**Comment by JO0st** [comment]
wat bedoel je met de studentencursus?

**Comment by JDevlieghere** [comment]
Ik vermoed dat hij de [cursus](https://github.com/KommuSoft/publications/tree/master/cursus_Artificiele_Intelligentie) van @KommuSoft bedoelt. Momenteel zijn zijn publicaties nog niet opgenomen in de lijst. Ik laat het initiatief daarvoor bij hem, als hij dat ziet zitten zet ik ze er met plezier tussen! :)
