### ISSUE TITLE
Wiskunde vakken

### ISSUE THREAD

**Issue by NorfairKing** [KULeuven-CS/kuleuven-cs.github.io#5]
Ik heb ook notities van wiskunde vakken:
- algebra
- meetkunde
- analyse
- kansrekenen

etc. 

Zet ik die er ook bij?

**Comment by JDevlieghere** [comment]
Zeker!

**Comment by NorfairKing** [comment]
Dat zijn vakken die niet in bach informatica of master CS voorkomen he...

**Comment by JDevlieghere** [comment]
Maar die wel keuzenvakken kunnen zijn? Je kunt ze eventueel onder een aparte sectie zetten als zijnde waardevolle achtergrond :-)

**Comment by NorfairKing** [comment]
Nee 't zijn gewoon wiskundevakken uit de bach wiskunde
